# Generated by Django 3.0.1 on 2020-08-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('DA', 'Dairy'), ('ME', 'Meat'), ('VE', 'Vegetable'), ('FR', 'Fruit'), ('GR', 'Grain')], default='DA', max_length=2),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(choices=[('RE', 'Refrigerator'), ('FR', 'Freezer'), ('CU', 'Cupboard')], default='RE', max_length=25),
        ),
    ]
